define description
A Xilitra limited port to run at WM8650 tablets
endef

CROSS_COMPILE=arm-xilitra-linux-uclibcgnueabi
STAGING=$(WORKDIR)/staging
#We need to set it to OPT to make our system run alongside android
#The actual prefix for programs will be $TC_PREFIX/$PREFIX. This is required, 
#so that we can make a working in /opt and do not require any chroot
TC_PREFIX=/opt

