#!/bin/bash

# 

archinit()
{
cat <<EOF
	comment "Select architectures to build packages against"
	comment "See extra menus for boards and variants"
EOF
}

addarch()
{
cat <<EOF
	menuconfig ARCH_$2
	bool "$1"
	
	if ARCH_$2
	source tmp/$1.kcnf
	endif
	
EOF
}

getdirs()
{
  find  $SRCDIR/$1/  -type d -maxdepth 1|while read line; do
  dir=`basename $line`
  db=`basename $1`
  if [ "$dir" != "$db" ]; then
    echo $dir
  fi
  done
}

genboards()
{
[ -f $SRCDIR/arch/$arch/kcnf ] && echo source arch/$arch/kcnf
getdirs $SRCDIR/arch/$arch/|while read line; do
  
  echo "menuconfig ${arch}_${line}" > $TEMPDIR/$arch.kcnf
  echo "bool \"$line\"" >> $TEMPDIR/$arch.kcnf
  echo "if ${arch}_${line}" >> $TEMPDIR/$arch.kcnf
  echo source arch/$arch/$line/kcnf >> $TEMPDIR/$arch.kcnf
  echo "endif" >> $TEMPDIR/$arch.kcnf
  
  echo "platforms-\$(CONFIG_${arch}_${line})+=arch/${arch}/${line}" >> $TEMPDIR/targets.mk
  
done
}


if [ "$1" == "deps" ]; then
  getdirs $SRCDIR/arch/|while read arch; do
    echo $SRCDIR/arch/$arch
    getdirs $SRCDIR/arch/$arch/|while read l; do
    echo $SRCDIR/arch/$arch/$l
    done
  done
else
  rm -f $TEMPDIR/arches.kcnf $TEMPDIR/targets.mk
  getdirs $SRCDIR/arch/|while read arch; do
  addarch "$arch" "`echo $arch | tr  [:lower:] [:upper:]`" >> $TEMPDIR/arches.kcnf
  genboards "$arch" "`echo $arch | tr  [:lower:] [:upper:]`" 
#   genrules "$arch" "`echo $arch | tr  [:lower:] [:upper:]`" > $TEMPDIR/
  done
fi
